Mage
adelestre/firestorm-hub pull request #21
Opened 2024-05-10 17:50 UTC by Yeobu

Add defensives & utility

2024-05-10 18:41 UTC, adelestre requested changes
J'ai commencé mais j'ai la flemme de terminer x) 
Tu peux fix ce que j'ai mis déjà, le reste ce sera juste de l'anglais et c'est pas hyper important.

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/damaging/AOERotation.tsx
> +      <YoutubeEmbed id="12c-MbY4PRQ" title="Fire mage opener.mp4" />
J'aurais pas mis .mp4, le `title` est juste utilisé pour donner quelque chose à l'attribut `alt` qui sert simplement au screen readers pour les malvoyants. Mettre dedans .mp4 c'est un peu redondant puisque le screen reader va déjà dire que c'est une vidéo. Il faut donc vraiment le voir comme un titre, ou un rapide description du contenu.

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/tips/DoublePyro.tsx
> +        much as possible on our target in ST scenarios at it's a 12% rough
```suggestion
        much as possible on our target in ST scenarios at it's a rough 12%
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/tips/DoublePyro.tsx
> +        and <ItemLink item={spells['fm-fireblast']} />, it's harder to do it
```suggestion
        and <ItemLink item={spells['fm-fireblast']} />, it's harder
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/tips/DoublePyro.tsx
> +        For this reason, the double Pyro is pretty usefull.
```suggestion
        For this reason, the double Pyro is pretty useful.
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/tips/DoublePyro.tsx
> +        During SKBs or combustion, when you start to be low on GC ressources (
```suggestion
        During SKBs or combustion, when you start to be low on GC resources (
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/tips/DoublePyro.tsx
> +        ), instead of doing GC, Pyro, GC, Pyro, GC, Pyro, etc. You will instead
```suggestion
        ), instead of doing GC, Pyro, GC, Pyro, GC, Pyro, etc. You should
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/tips/DoublePyro.tsx
> +// import items from '@shared/items.json'
C'est plus propre de supprimer les imports plutôt que de les commenter. Si tu as de nouveau besoin d'importer quelque chose, c'est plus rapide de rajouter l'import avec l'import automatique de VS Code plutôt que de retrouver si il était déjà là mais commenté etc...: 
![image](https://github.com/adelestre/firestorm-hub/assets/72563434/88684f65-c125-4336-b52a-87044429d8a9)

C'est juste un commentaire pour la suite, t'embête pas avec ça tout de suite.

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/tips/Tips.tsx
> +        This part will provide you some advanced tips and tricks that will help
```suggestion
        This part will provide you with some advanced tips and tricks that will help
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/tips/Tips.tsx
> +        you reach higher DPS and/or uptime DPS. There is a lot to cover on here,
```suggestion
        you reach higher DPS and/or uptime DPS. There is a lot to cover here,
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/utility/CC.tsx
> +        powerfull CC, especially in combination with our talent{' '}
```suggestion
        powerful CC, especially in combination with our talent{' '}
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/utility/CC.tsx
> +        pretty powerfull, also interesting for its positionning purposes as it
```suggestion
        pretty powerful, also interesting for its positionning purposes as it
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/utility/CC.tsx
> +        allows you to remove adds from Sanguine affix for exemple, in these
```suggestion
        allows you to remove adds from the Sanguine affix for exemple. In those
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/utility/CC.tsx
> +        situation you can also bring the talent{' '}
```suggestion
        situations you can also bring the talent{' '}
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/utility/CC.tsx
> +        if you teams need even more CC.
```suggestion
        if your teams need even more CC.
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/utility/CC.tsx
> +        We also bring a ton of freezes though{' '}
```suggestion
        We also bring a ton of freezes through{' '}
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/utility/CC.tsx
> +        take care as if you sheep a target or use{' '}
```suggestion
       be aware though that using sheep on a target or using{' '}
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/utility/CC.tsx
> +        combat. You can still pull some skips using sheep and running when you
```suggestion
        combat. You can still pull out some skips using sheep and running when you
```

2024-05-10 18:41 UTC, adelestre commented on src/components/specs/mage/fire/mythic-plus/gameplay/utility/CC.tsx
> +        need to so your group can safely follow you without beeing in combat,
```suggestion
        need to so your group can safely follow you without being in combat,
```

2024-05-10 22:05 UTC, Yeobu commented on src/components/specs/mage/fire/mythic-plus/gameplay/tips/DoublePyro.tsx
> +// import items from '@shared/items.json'
Oui je suis d'accord, c'est surtout des copiés collés de fichiers pour aller plus vite et je commente les erreurs, mais je suis d'accord c'est bien plus clean de supprimer les imports inutiles

2024-05-13 10:04 UTC, adelestre approved these changes

2024-05-13 10:05 UTC, merged